# Generated by Django 2.0.7 on 2019-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15, null=True, verbose_name='auth.User')),
                ('first_name', models.CharField(default='user', max_length=15)),
                ('last_name', models.CharField(default='user', max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=4)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
